Update git submodules
* Update docs/submodules/sdc/sdc-workflow-designer.git from branch 'master'
  to c54aacb32df8fcb27375d1b131f76afc0a34d0c7
  - Use versioning, zusammen and session libs from sdc-common-be
    
    zusammen-lib in sdc-common-be uses cassandra 3.6.0 withoutJMXReporting
    (cassandra 3.4.0 with spring boot 2.1.0 caused:
    java.lang.NoClassDefFoundError: com/codahale/metrics/JmxReporter)
    
    Change-Id: I248442d519b2ad5f4869e9384e447e9004d24586
    Issue-ID: SDC-2541
    Signed-off-by: talig <talig@amdocs.com>