Update git submodules
* Update docs/submodules/sdc/sdc-workflow-designer.git from branch 'master'
  to 1d5ecc692a165fc84181b8f145242a410f2abf38
  - Fix throwing an UnsatisfiedDependencyException upon starting
    
    The UnsatisfiedDependencyException is finally caused by
    ClassNotFoundException: c.g.c.u.c.FutureFallback.
    That was fixed by upgrading the spring boot version to 2.1.0.RELEASE.
    By doing that the cassandra version was upgraded to version 3.6.0,
    which doesn't require the FutureFallback class.
    
    Issue-ID: SDC-2557
    Signed-off-by: Piotr Borelowski <p.borelowski@partner.samsung.com>
    Change-Id: I5b319096978e768b7520fb937fd2b3dad26f15c5