Update git submodules
* Update docs/submodules/vid.git from branch 'master'
  to efefd95854efb51333dc36abe7bb33fca4d04e90
  - Add c3p0 connection pooling to ext-svc-simulator
    
    Should avoid login errors like
       java.io.IOException: Server returned HTTP response code: 500 for URL: http://ci-cd-simulator-service:8080/vidSimulator/.../auxapi//v3/user/us16807000
    when those are due to tenured connections.
    
    Issue-ID: VID-647
    
    Change-Id: I17ce716114535487e2e4a90c558c0334af5494fd
    Signed-off-by: Ittay Stern <ittay.stern@att.com>