Update git submodules
* Update docs/submodules/oom.git from branch 'master'
  to ff079f9ffdf08c3f39b496bd06cea04f3be0a2e4
  - Merge "[SDNC] Correct config directories for ODL"
  - [SDNC] Correct config directories for ODL
    
    SDNC entrypoint script sets up several environment variables
    including configfiles dir. Recent addition of AAF configfiles
    broke expected path for used properties files. This could be
    noticed with example error from karaf logs:
    org.onap.ccsdk.sli.core.sli.SvcLogicException: Cannot read property file: /opt/app/osaaf/local/generic-resource-api-dg.properties: /opt/app/osaaf/local/generic-resource-api-dg.properties (No such file or directory)
    
    Issue-ID: SDNC-1147
    Signed-off-by: Konrad Bańka <k.banka@samsung.com>
    Change-Id: Ifcfde9abef1c12a7b8d1009f346d313b8fe57f44